### ISSUE TITLE
Unnecessary Simulation Check

### ISSUE THREAD

**Issue by CoolSpy3** [DeepBlueRobotics/lib199#44]
https://github.com/DeepBlueRobotics/lib199/blob/432cd16685f4d50eafe6f345dd897543401f1cae/src/main/java/org/carlmontrobotics/lib199/MotorControllerFactory.java#L122 It looks like Rev might've fixed the need for this in [2022.1.0](https://docs.revrobotics.com/sparkmax/software-resources/spark-max-api-information). Someone should investigate.

**Comment by brettle** [comment]
Looks like this was fixed [here](https://github.com/DeepBlueRobotics/lib199/commit/741d46b6921c617f4bf4a730b9a8d624ea437f69).

**Comment by CoolSpy3** [comment]
Could you clarify? The check remains in-place here. The point of this issue (although, I admit my description above is terrible) was to investigate whether rev simulation (or at least the necessity of not calling rev constructors in sim) was still relevant after the listed update. If it wasn't the simulation check could be removed, and we could possibly investigate less-hacky (non-Mockito) ways to perform simulation.

**Comment by brettle** [comment]
Oh. I misunderstood and thought you were referring to something else.

To answer your question, I believe the rev update you are referring to prevents *crashing* when the calling constructors in sim (though I haven't verified on all platforms), *but* the actual simulation support it provides is not connected to the wpilib sim infrastructure at all. As a result, I believe we still need the mock.

**Comment by CoolSpy3** [comment]
Good to know. Although, if the constructor no longer crashes the simulation, the idea was that we could consider extending `CANSparkMax` and simply overriding the relevant methods, which may have less overhead than Mockito (although, it would make our Mock classes less generalizable).

**Comment by brettle** [comment]
Oh. Why didn't I think of subclassing?! Can you create a separate issue to investigate doing that and in it describe in more detail what you see as the possible advantages/disadvantages?

**Comment by CoolSpy3** [comment]
[Done!](https://github.com/DeepBlueRobotics/lib199/issues/101)
