### ISSUE TITLE
Possible Unnecessary Code (Check REVLib Changelog) (SparkMax Unplugged Warning)

### ISSUE THREAD

**Issue by CoolSpy3** [DeepBlueRobotics/lib199#45]
https://github.com/DeepBlueRobotics/lib199/blob/432cd16685f4d50eafe6f345dd897543401f1cae/src/main/java/org/carlmontrobotics/lib199/MotorControllerFactory.java#L124-L128 I've emailed Rev about the REVLib issue for which this is a workaround. This issue is for discussion of any relevant information, and as a reminder to watch the changelog as a supported solution may be released in the future.

**Comment by CoolSpy3** [comment]
As far as I can tell, this has been patched. I tried creating a spark-max with id 99 and setting the speed, and it didn't crash the code. Some pros and cons to keeping this in:
Pros
* We get a warning when a SparkMax is unplugged
* Known behavior of disconnected SparkMaxes

Cons
* When there are REVLib changes, the dummy spark max implementation has to be updated or stuff starts breaking
* Mockito overhead

Please provide thoughts below

**Comment by brettle** [comment]
[This post](https://www.chiefdelphi.com/t/can-spark-max-unable-to-retrieve-spark-max-firmware-version-for-can-id-0/376796/2) seems to indicate that RevLib already logs an error if you attempt to communicate with an unplugged SparkMax, so I don't see a good reason to keep the code.

**Comment by CoolSpy3** [comment]
Confirmed! I'll start a PR.
