### ISSUE TITLE
Possible Unnecessary Code (Check REVLib Changelog) (CachedSparkMax)

### ISSUE THREAD

**Issue by CoolSpy3** [DeepBlueRobotics/lib199#46]
https://github.com/DeepBlueRobotics/lib199/blob/432cd16685f4d50eafe6f345dd897543401f1cae/src/main/java/org/carlmontrobotics/lib199/CachedSparkMax.java#L1-L28 I've emailed Rev about the REVLib issue for which this is a workaround. This issue is for discussion of any relevant information, and as a reminder to watch the changelog as a supported solution may be released in the future.

**Comment by CoolSpy3** [comment]
It looks like all the relevant methods in CANSparkMax have been rewritten to cache their return values. Rev's implementation also has better thread safety than the one here. I'll start a PR to deprecate this class. It should be removed in the next major version.

**Comment by ProfessorAtomicManiac** [comment]
where do you find these changelogs? I looked up "Rev robotics changelog" and other keywords but couldn't find it anywhere.

**Comment by CoolSpy3** [comment]
> where do you find these changelogs? I looked up "Rev robotics changelog" and other keywords but couldn't find it anywhere.

They're on the [REVLib information page](https://docs.revrobotics.com/sparkmax/software-resources/spark-max-api-information)
