### ISSUE TITLE
Get rid of old branches

### ISSUE THREAD

**Issue by ProfessorAtomicManiac** [DeepBlueRobotics/lib199#58]
We should probably still check if they are important but some of the branches are from years ago so I doubt they would be useful.

**Comment by CoolSpy3** [comment]
I've tried to go through and get most of them. A couple final notes:
`no-temp-limit-old` - This branch contains outdated code but I thing it's still the bug it patches is still present in 4.0.2, so we should probably wait until the release of 5.0.0 and then some before deleting it.
`Command-Logger` - @ProfessorAtomicManiac This is your branch. Is it still used anywhere or can we delete it?

**Comment by CoolSpy3** [comment]
Completed by @brettle, @ProfessorAtomicManiac, @FriedLongJohns, and myself in-person two days ago.
